### ISSUE TITLE
ABI.Ninja UI overlap

### ISSUE THREAD

**Issue by ZakGriffith** [BuidlGuidl/hacked-wallet-recovery#37]
When adding assets manually and clicking into ABI.Ninja, the logo at the top of the area is cutoff, and the Quick Access text overlaps the footer text.  This overlap persists when scrolling. Tested on a resolutions 2560x1440(Windows) and 1511x981(Macbook Pro)

![image](https://github.com/user-attachments/assets/12c58828-9f22-4487-bba3-723f0aec405a)

**Comment by KcPele** [comment]
working on this
