### ISSUE TITLE
Set up testnet

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/hacked-wallet-recovery#62]
There are parts of the app were we assume goerli as the testnet. Flashbots does not seem to work on Goerli but they have added support for sepolia and holesky so it would be expedient to switch to one of those for testing purposes.

**Comment by portdeveloper** [comment]
May I take this one?

**Comment by escottalexander** [comment]
Sure! Let me know if you hit any roadblocks

**Comment by escottalexander** [comment]
Fixed: https://github.com/BuidlGuidl/hacked-wallet-recovery/pull/65
